### ISSUE TITLE
Would like contribute.

### ISSUE THREAD

**Issue by shubhamnba2009** [HumanAgainstMachine/ebay-listing-grid#1]
Hi!! 
I would like to contribute, it will be helpful if you can guide how to get started. I was too enrolled in previous html5 course on edX. Willing to apply my knowledeg in open source project.
Thanks in advance for help

**Comment by HumanAgainstMachine** [comment]
Hello and welcome,

actually I don't see right now ways to improve the project, rather I see ways to extend it.
To start, you could 
either use ELG to create a new appealing template example, if you are able to design a layout 
or write in plain javascript a solution to caution number 2.

**Comment by HumanAgainstMachine** [comment]
.... Let me know if this fits to you.

**Comment by shubhamnba2009** [comment]
I am a learner, tat's why it can take me some time to help in contribution. But will sure help in exapanding through ideas given by you. I think these suits me, I'll start working in one of those. And thanks for the heads up

**Comment by HumanAgainstMachine** [comment]
I am looking forward to add your contributes to this project.
If you need suggestions, you are welcome to ask.
